package WLaberge;

public class ChangeMakerKata {

	public static void main(String[] arg) {
		// call makeChange using pennify to send integer values of doubles for price and amount received
		
	}

	/* 
	 * makeChange Method
   * Find the total of the other types of change using division and modulus.
	 * calls showChange to display result
	 * 
	 * @param int price, int received.
	 * @return none
	 */
	
		//define changePennies as received - price
		
		// define a for loop to determine amount of change of each coin starting with quarters
		
			// use Math.floor to determine how many of target coin is part of change
			
			// set changePennies = to modulus(remainder)
			

	/*
	 * showChange Method
   * Use a for loop to show the amount of each type of change in an array.
	 * 
	 * 
	 * 
	 */
	
	/*
	 * pennify Method
   * Converts a double to an integer.
	 * 
	 * @param buckNChange
	 * @return (int) pennies
	 */

	/*
	 * coins Array
   * Creates an array that give us the value of each coin type.
	 * 
	 * 
	 * 
	 */
	
	/*
	 * allChange Array
   * Creates an array that we place the exact number of each coin type.
	 * 
	 * 
	 * 
	 */
	
	
	
}
